project_id = "dmgbocugghekzsdptrgj"

[functions.text-to-speech]
verify_jwt = false

[functions.generate-avatar]
verify_jwt = false

[functions.generate-story]
verify_jwt = false

[functions.generate-enhanced-story]
verify_jwt = false

[functions.generate-story-illustrations]
verify_jwt = false

[functions.generate-story-narration]
verify_jwt = false

[functions.child-chat]
verify_jwt = false

[functions.match-content]
verify_jwt = false
