project_id = "dmgbocugghekzsdptrgj"

[functions.text-to-speech]
verify_jwt = false

[functions.generate-avatar]
verify_jwt = false

[functions.generate-story]
verify_jwt = false

[functions.child-chat]
verify_jwt = false
